name: PySAT Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest setuptools wheel
      - name: Build and install wheel
        run: |
          python setup.py bdist_wheel
          pip install dist/*.whl
      - name: Test with pytest
        run: |
          pytest
